## Filtering

In [ ]:
import pandas as pd
people = {
    "first" : ["Devraj","Yash", "Tarun"],
    "last" : ["Charan", "Burad", "Yadav"],
    "email" : ["devrajcharan@gmail.com", "yashburad@gmail.com", "tarunyadav@gmail.com"]
}
df = pd.DataFrame(people)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [ ]:
filt = df['first'] == 'Devraj'
df[filt]
#you can also
df[df['first']=='Devraj'] #without assigning variable

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com

In [ ]:
df.loc[filt]

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com

In [ ]:
#you can also get specific column by using df.loc
df.loc[filt, 'email']

0    devrajcharan@gmail.com
Name: email, dtype: object

In [ ]:
filt = (df['last'] == 'Charan') & (df['first'] == 'Devraj')
df.loc[filt]

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com

In [ ]:
filt = (df['first'] == 'Devraj') | (df['last'] == 'Yadav')
df.loc[filt, 'email']

0    devrajcharan@gmail.com
2      tarunyadav@gmail.com
Name: email, dtype: object

In [ ]:
#you can also use '~' for negation of filter
df.loc[~filt, 'email']

1    yashburad@gmail.com
Name: email, dtype: object

In [ ]:
# for multiple filters, 
# 1.) make a list
first = ['Devraj','Yash']
# 2.) us df['column'].isin(list_name)
filt = df['first'].isin(first)
df.loc[filt]

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com

## String Method

In [ ]:
#To check is the string contains specific word
filt = df['email'].str.contains('devraj')
df.loc[filt,['first','last']]

    first    last
0  Devraj  Charan