## Indexing, and operations

In [1]:
import pandas as pd
# dictionary = { key : value }
people = {
    "first" : ["Devraj","Yash", "Tarun"],
    "last" : ["Charan", "Burad", "Yadav"],
    "email" : ["devrajcharan@gmail.com", "yashburad@gmail.com", "tarunyadav@gmail.com"]
}
# here keys are columns if we convert into data frame
#to access use keys ->  dictionary[key]
df = pd.DataFrame(people)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [2]:
#To set any column as index -> df.set_index('name')
# we can aslo use df = pd.read_csv('filename.csv', index_col = 'col_name')
df.set_index('email')
#but it won't change the index permanently

                         first    last
email
devrajcharan@gmail.com  Devraj  Charan
yashburad@gmail.com       Yash   Burad
tarunyadav@gmail.com     Tarun   Yadav

In [3]:
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [4]:
#To change index permanently -> df.set_index('name', inplace = True)
df.set_index('email', inplace = True)

In [5]:
df

                         first    last
email
devrajcharan@gmail.com  Devraj  Charan
yashburad@gmail.com       Yash   Burad
tarunyadav@gmail.com     Tarun   Yadav

In [6]:
#To see all index/indices
df.index #we need these to find certain row

Index(['devrajcharan@gmail.com', 'yashburad@gmail.com',
       'tarunyadav@gmail.com'],
      dtype='object', name='email')

In [7]:
df.loc['tarunyadav@gmail.com']

first    Tarun
last     Yadav
Name: tarunyadav@gmail.com, dtype: object

In [8]:
df.reset_index(inplace = True)
df

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav

In [9]:
#to sort indexes -> df.sort_index
df1  = df.set_index('email')
df1.sort_index()

                         first    last
email
devrajcharan@gmail.com  Devraj  Charan
tarunyadav@gmail.com     Tarun   Yadav
yashburad@gmail.com       Yash   Burad

In [10]:
#To reverse sort the index
df.sort_index(ascending = False)

                    email   first    last
2    tarunyadav@gmail.com   Tarun   Yadav
1     yashburad@gmail.com    Yash   Burad
0  devrajcharan@gmail.com  Devraj  Charan

In [11]:
#to sort permanently
df1.sort_index(inplace = True)
df1

                         first    last
email
devrajcharan@gmail.com  Devraj  Charan
tarunyadav@gmail.com     Tarun   Yadav
yashburad@gmail.com       Yash   Burad