## Add/Remove rows and columns

In [166]:
import pandas as pd
people = {
    "first" : ["Devraj","Yash", "Tarun"],
    "last" : ["Charan", "Burad", "Yadav"],
    "email" : ["devrajcharan@gmail.com", "yashburad@gmail.com", "tarunyadav@gmail.com"]
}
df = pd.DataFrame(people)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

## For columns

In [167]:
# TO add columns -> df['col1'] + ' ' + df['col2']
df['first'] + ' ' + df['last']

0    Devraj Charan
1       Yash Burad
2      Tarun Yadav
dtype: object

In [168]:
#To make a new column for first and last
df['full_name'] = df['first'] + ' ' + df['last']
df

    first    last                   email      full_name
0  Devraj  Charan  devrajcharan@gmail.com  Devraj Charan
1    Yash   Burad     yashburad@gmail.com     Yash Burad
2   Tarun   Yadav    tarunyadav@gmail.com    Tarun Yadav

In [169]:
#To remove columns -> df.drop(columns = [<columns names>])
df.drop(columns = ['first', 'last']) #won't change original

                    email      full_name
0  devrajcharan@gmail.com  Devraj Charan
1     yashburad@gmail.com     Yash Burad
2    tarunyadav@gmail.com    Tarun Yadav

In [170]:
df

    first    last                   email      full_name
0  Devraj  Charan  devrajcharan@gmail.com  Devraj Charan
1    Yash   Burad     yashburad@gmail.com     Yash Burad
2   Tarun   Yadav    tarunyadav@gmail.com    Tarun Yadav

In [171]:
df.drop(columns = ['first', 'last'], inplace = True)
df

                    email      full_name
0  devrajcharan@gmail.com  Devraj Charan
1     yashburad@gmail.com     Yash Burad
2    tarunyadav@gmail.com    Tarun Yadav

In [172]:
# to split a column-> use string split()
df['full_name'].str.split(' ')

0    [Devraj, Charan]
1       [Yash, Burad]
2      [Tarun, Yadav]
Name: full_name, dtype: object

In [173]:
# to split columns into columns -> after split( ,expand=True)
df['full_name'].str.split(' ', expand = True)

        0       1
0  Devraj  Charan
1    Yash   Burad
2   Tarun   Yadav

In [174]:
#To add these columns in DataFrame
df[['first','last']] = df['full_name'].str.split(' ', expand = True)
df.drop(columns = ['full_name'], inplace = True)
df

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav

## For rows

In [175]:
#To add row
first = {'first' : ['Aryan']}
df1 = pd.DataFrame(first)
df_new = pd.concat([df, df1])
df_new

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav
0                     NaN   Aryan     NaN

In [176]:
people2 = {
    "first" : ["Pradyumn","Aryan"],
    "last" : ["Krishna", "Sharma"],
    "email" : ["pradyumnkrishna@gmail.com", "aryansharma@gmail.com"]
}
df2 = pd.DataFrame(people2)
df2

      first     last                      email
0  Pradyumn  Krishna  pradyumnkrishna@gmail.com
1     Aryan   Sharma      aryansharma@gmail.com

In [177]:
#to add rows of one DataFrame to another
df = pd.concat([df,df2], ignore_index = True)
df

                       email     first     last
0     devrajcharan@gmail.com    Devraj   Charan
1        yashburad@gmail.com      Yash    Burad
2       tarunyadav@gmail.com     Tarun    Yadav
3  pradyumnkrishna@gmail.com  Pradyumn  Krishna
4      aryansharma@gmail.com     Aryan   Sharma

In [179]:
#to remove rows -> df.drop(index = index of row)
df.drop(index = 3)

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav
4   aryansharma@gmail.com   Aryan  Sharma

In [181]:
df.drop(index = 3, inplace = True)

In [183]:
df

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav
4   aryansharma@gmail.com   Aryan  Sharma

In [185]:
#you can also apply filter while using drop
filt = df['last'] == 'Sharma'
df.drop(index = df[filt].index)

                    email   first    last
0  devrajcharan@gmail.com  Devraj  Charan
1     yashburad@gmail.com    Yash   Burad
2    tarunyadav@gmail.com   Tarun   Yadav