In [ ]:
import pandas as pd

## Dictionary

In [ ]:
# dictionary = { key : value }
people = {
    "first" : ["Devraj","Yash", "Tarun"],
    "last" : ["Charan", "Burad", "Yadav"],
    "email" : ["devrajcharan@gmail.com", "yashburad@gmail.com", "tarunyadav@gmail.com"]
}
# here keys are columns if we convert into data frame
#to access use keys ->  dictionary[key]
people ['email']

['devrajcharan@gmail.com', 'yashburad@gmail.com', 'tarunyadav@gmail.com']

In [ ]:
#To convert it into 'Data Frame'
df1 = pd.DataFrame(people)
df1

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [ ]:
#To convert it into 'Data Frame'
df1 = pd.DataFrame(people)
df1

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [ ]:
#to access a single column -> df[column_name]
df1['email']

0    devrajcharan@gmail.com
1       yashburad@gmail.com
2      tarunyadav@gmail.com
Name: email, dtype: object

In [ ]:
#i single column of a data frame is a series,
#data frame is also k/as containor for multiple series
type(df1['email'])

pandas.core.series.Series

In [ ]:
#column of a data frame can also be accessed by -> df.column_name
#using this method can have problem  if column_name is same as one of the attributes/method of data frame
df1.email

0    devrajcharan@gmail.com
1       yashburad@gmail.com
2      tarunyadav@gmail.com
Name: email, dtype: object

In [ ]:
#to access multiple columns at same time
df1[['first','last']]

    first    last
0  Devraj  Charan
1    Yash   Burad
2   Tarun   Yadav

In [ ]:
#to access all column names
df1.columns

Index(['first', 'last', 'email'], dtype='object')

In [ ]:
#to access rows and columns both (by index)
df1.iloc[[0,1], [0,2]]

    first                   email
0  Devraj  devrajcharan@gmail.com
1    Yash     yashburad@gmail.com

In [ ]:
df1

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [ ]:
#to access rows, columns by label -> df.loc
df1.loc[[0,1],['first', 'email']]

    first                   email
0  Devraj  devrajcharan@gmail.com
1    Yash     yashburad@gmail.com